// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use jc_core::{Input, DIM};
use methods::{JUSTCASH_ELF, JUSTCASH_ID};
use risc0_zkvm::{default_prover, Digest, ExecutorEnv, Receipt};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Pick two numbers
    let input = Input {
        hashes: [Digest::ZERO; DIM],
        directions: [0; DIM],
        sk: Digest::ZERO,
        nk: Digest::ZERO,
    };
    let receipt = prove(input);
    // Here is where one would send 'receipt' over the network...
    // Verify receipt, panic if it's wrong
    receipt.verify(JUSTCASH_ID).expect(
        "Code you have proven should successfully verify; did you specify the correct image ID?",
    );
}

pub fn prove(input: Input) -> Receipt {
    // For example:
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, JUSTCASH_ELF).unwrap();

    // extract the receipt.
    prove_info.receipt
}
