// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{JUSTCASH_ID};
use methods::{JUSTCASH_ELF};
use risc0_zkvm::{default_prover, ExecutorEnv, Receipt};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Pick two numbers
    let (receipt, _) = multiply(17, 23);
    // Here is where one would send 'receipt' over the network...
    // Verify receipt, panic if it's wrong
    receipt.verify(JUSTCASH_ID).expect(
        "Code you have proven should successfully verify; did you specify the correct image ID?",
    );
}



pub fn multiply(a: u64, b: u64) -> (Receipt, u64) {
    // For example:
    let env = ExecutorEnv::builder()
        .write(&a)
        .unwrap()
        .write(&b)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover
        .prove(env, JUSTCASH_ELF)
        .unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.

    // For example:
    let _output: u64 = receipt.journal.decode().unwrap();

    (receipt, _output)

}


