// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
pub use justcash_core::Input;
use justcash_methods::JUSTCASH_ELF;
pub use risc0_zkvm::Receipt;
use risc0_zkvm::{default_prover, ExecutorEnv};

pub fn init() {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();
}

pub fn prove(input: Input) -> Receipt {
    // For example:
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, JUSTCASH_ELF).unwrap();

    // extract the receipt.
    prove_info.receipt
}
